# Generated by Django 2.2.28 on 2022-12-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Cost', models.EmailField(max_length=254)),
                ('Shop', models.CharField(max_length=50)),
                ('Adress', models.CharField(max_length=50)),
            ],
        ),
    ]
