# Generated by Django 2.2.28 on 2022-12-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='Adress',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='Shop',
            new_name='shop',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='Cost',
        ),
        migrations.AddField(
            model_name='medicine',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
