# Generated by Django 2.2.28 on 2022-12-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20221209_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.TextField(max_length=250)),
                ('password', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=60)),
                ('mobile', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
