# Generated by Django 2.2.28 on 2022-12-16 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
